export const dataMunicipality = [
  ["Amazonas", "Leticia"],
  ["Amazonas", "Puerto Nariño"],
  ["Antioquia", "Abejorral"],
  ["Antioquia", "Abriaquí"],
  ["Antioquia", "Alejandría"],
  ["Antioquia", "Amaga"],
  ["Antioquia", "Amalfi"],
  ["Antioquia", "Andes"],
  ["Antioquia", "Angelópolis"],
  ["Antioquia", "Angostura"],
  ["Antioquia", "Anorí"],
  ["Antioquia", "Anzá"],
  ["Antioquia", "Apartadó"],
  ["Antioquia", "Arboletes"],
  ["Antioquia", "Argelia"],
  ["Antioquia", "Armenia"],
  ["Antioquia", "Barbosa"],
  ["Antioquia", "Bello"],
  ["Antioquia", "Belmira"],
  ["Antioquia", "Betania"],
  ["Antioquia", "Betulia"],
  ["Antioquia", "Briceño"],
  ["Antioquia", "Buriticá"],
  ["Antioquia", "Cáceres"],
  ["Antioquia", "Caicedo"],
  ["Antioquia", "Caldas"],
  ["Antioquia", "Campamento"],
  ["Antioquia", "Cañasgordas"],
  ["Antioquia", "Caracolí"],
  ["Antioquia", "Caramanta"],
  ["Antioquia", "Carepa"],
  ["Antioquia", "Carolina Del Principe"],
  ["Antioquia", "Caucasia"],
  ["Antioquia", "Chigorodó"],
  ["Antioquia", "Cisneros"],
  ["Antioquia", "Ciudad Bolívar"],
  ["Antioquia", "Cocorná"],
  ["Antioquia", "Concepción"],
  ["Antioquia", "Concordia"],
  ["Antioquia", "Copacabana"],
  ["Antioquia", "Dabeiba"],
  ["Antioquia", "Don Matías"],
  ["Antioquia", "Ebéjico"],
  ["Antioquia", "El Bagre"],
  ["Antioquia", "El Carmen De Viboral"],
  ["Antioquia", "El Peñol"],
  ["Antioquia", "El Retiro"],
  ["Antioquia", "Entrerríos"],
  ["Antioquia", "Envigado"],
  ["Antioquia", "Fredonia"],
  ["Antioquia", "Frontino"],
  ["Antioquia", "Giraldo"],
  ["Antioquia", "Girardota"],
  ["Antioquia", "Gómez Plata"],
  ["Antioquia", "Granada"],
  ["Antioquia", "Guadalupe"],
  ["Antioquia", "Guarne"],
  ["Antioquia", "Guatapé"],
  ["Antioquia", "Heliconia"],
  ["Antioquia", "Hispania"],
  ["Antioquia", "Itagüí"],
  ["Antioquia", "Ituango"],
  ["Antioquia", "Jardín"],
  ["Antioquia", "Jericó"],
  ["Antioquia", "La Ceja Del Tambo"],
  ["Antioquia", "La Estrella"],
  ["Antioquia", "La Pintada"],
  ["Antioquia", "La Unión"],
  ["Antioquia", "Liborina"],
  ["Antioquia", "Maceo"],
  ["Antioquia", "Marinilla"],
  ["Antioquia", "Medellín"],
  ["Antioquia", "Montebello"],
  ["Antioquia", "Murindó"],
  ["Antioquia", "Mutatá"],
  ["Antioquia", "Nariño"],
  ["Antioquia", "Nechí"],
  ["Antioquia", "Necoclí"],
  ["Antioquia", "Olaya"],
  ["Antioquia", "Peque"],
  ["Antioquia", "Pueblorrico"],
  ["Antioquia", "Puerto Berrio"],
  ["Antioquia", "Puerto Nare"],
  ["Antioquia", "Puerto Triunfo"],
  ["Antioquia", "Remedios"],
  ["Antioquia", "Rionegro"],
  ["Antioquia", "Sabanalarga"],
  ["Antioquia", "Sabaneta"],
  ["Antioquia", "Salgar"],
  ["Antioquia", "San Andrés De Cuerquia"],
  ["Antioquia", "San Carlos"],
  ["Antioquia", "San Francisco"],
  ["Antioquia", "San Jerónimo"],
  ["Antioquia", "San José De La Montaña"],
  ["Antioquia", "San Juan De Urabá"],
  ["Antioquia", "San Luis"],
  ["Antioquia", "San Pedro De Los Milagros"],
  ["Antioquia", "San Pedro De Urabá"],
  ["Antioquia", "San Rafael"],
  ["Antioquia", "San Roque"],
  ["Antioquia", "San Vicente"],
  ["Antioquia", "Santa Bárbara"],
  ["Antioquia", "Santa Rosa De Osos"],
  ["Antioquia", "Santafe De Antioquia"],
  ["Antioquia", "Santo Domingo"],
  ["Antioquia", "Santuario"],
  ["Antioquia", "Segovia"],
  ["Antioquia", "Sonsón"],
  ["Antioquia", "Sopetrán"],
  ["Antioquia", "Támesis"],
  ["Antioquia", "Tarazá"],
  ["Antioquia", "Tarso"],
  ["Antioquia", "Titiribí"],
  ["Antioquia", "Toledo"],
  ["Antioquia", "Turbo"],
  ["Antioquia", "Uramita"],
  ["Antioquia", "Urrao"],
  ["Antioquia", "Valdivia"],
  ["Antioquia", "Valparaíso"],
  ["Antioquia", "Vegachí"],
  ["Antioquia", "Venecia"],
  ["Antioquia", "Vigía Del Fuerte"],
  ["Antioquia", "Yalí"],
  ["Antioquia", "Yarumal"],
  ["Antioquia", "Yolombó"],
  ["Antioquia", "Yondo"],
  ["Antioquia", "Zaragoza"],
  ["Arauca", "Arauca"],
  ["Arauca", "Arauquita"],
  ["Arauca", "Cravo Norte"],
  ["Arauca", "Fortul"],
  ["Arauca", "Puerto Rondón"],
  ["Arauca", "Saravena"],
  ["Arauca", "Tame"],
  ["Atlántico", "Baranoa"],
  ["Atlántico", "Barranquilla"],
  ["Atlántico", "Campo De La Cruz"],
  ["Atlántico", "Candelaria"],
  ["Atlántico", "Galapa"],
  ["Atlántico", "Juan De Acosta"],
  ["Atlántico", "Luruaco"],
  ["Atlántico", "Malambo"],
  ["Atlántico", "Manatí"],
  ["Atlántico", "Palmar De Varela"],
  ["Atlántico", "Piojo"],
  ["Atlántico", "Polonuevo"],
  ["Atlántico", "Ponedera"],
  ["Atlántico", "Puerto Colombia"],
  ["Atlántico", "Repelón"],
  ["Atlántico", "Sabanagrande"],
  ["Atlántico", "Sabanalarga"],
  ["Atlántico", "Santa Lucía"],
  ["Atlántico", "Santo Tomas"],
  ["Atlántico", "Soledad"],
  ["Atlántico", "Suan"],
  ["Atlántico", "Tubará"],
  ["Atlántico", "Usiacurí"],
  ["Bolívar", "Achí"],
  ["Bolívar", "Altos Del Rosario"],
  ["Bolívar", "Arenal"],
  ["Bolívar", "Arjona"],
  ["Bolívar", "Arroyohondo"],
  ["Bolívar", "Barranco De Loba"],
  ["Bolívar", "Calamar"],
  ["Bolívar", "Cantagallo"],
  ["Bolívar", "Cartagena de Indias"],
  ["Bolívar", "Cicuco"],
  ["Bolívar", "Clemencia"],
  ["Bolívar", "Córdoba"],
  ["Bolívar", "El Carmen De Bolívar"],
  ["Bolívar", "El Guamo"],
  ["Bolívar", "El Peñon"],
  ["Bolívar", "Hatillo De Loba"],
  ["Bolívar", "Magangué"],
  ["Bolívar", "Mahates"],
  ["Bolívar", "Margarita"],
  ["Bolívar", "María La Baja"],
  ["Bolívar", "Montecristo"],
  ["Bolívar", "Morales"],
  ["Bolívar", "Norosí"],
  ["Bolívar", "Pinillos"],
  ["Bolívar", "Regidor"],
  ["Bolívar", "Rioviejo"],
  ["Bolívar", "San Cristóbal"],
  ["Bolívar", "San Estanislao"],
  ["Bolívar", "San Fernando"],
  ["Bolívar", "San Jacinto"],
  ["Bolívar", "San Jacinto Del Cauca"],
  ["Bolívar", "San Juan Nepomuceno"],
  ["Bolívar", "San Martín De Loba"],
  ["Bolívar", "San Pablo"],
  ["Bolívar", "Santa Catalina"],
  ["Bolívar", "Santa Cruz De Mompós"],
  ["Bolívar", "Santa Rosa Del Norte"],
  ["Bolívar", "Santa Rosa Del Sur"],
  ["Bolívar", "Simití"],
  ["Bolívar", "Soplaviento"],
  ["Bolívar", "Talaigua Nuevo"],
  ["Bolívar", "Tiquisio"],
  ["Bolívar", "Turbaco"],
  ["Bolívar", "Turbana"],
  ["Bolívar", "Villanueva"],
  ["Bolívar", "Zambrano"],
  ["Boyacá", "Almeida"],
  ["Boyacá", "Aquitania"],
  ["Boyacá", "Arcabuco"],
  ["Boyacá", "Belén"],
  ["Boyacá", "Berbeo"],
  ["Boyacá", "Betéitiva"],
  ["Boyacá", "Boavita"],
  ["Boyacá", "Boyacá"],
  ["Boyacá", "Briceño"],
  ["Boyacá", "Buenavista"],
  ["Boyacá", "Busbanzá"],
  ["Boyacá", "Caldas"],
  ["Boyacá", "Campohermoso"],
  ["Boyacá", "Cerinza"],
  ["Boyacá", "Chinavita"],
  ["Boyacá", "Chiquinquirá"],
  ["Boyacá", "Chíquiza"],
  ["Boyacá", "Chiscas"],
  ["Boyacá", "Chita"],
  ["Boyacá", "Chitaraque"],
  ["Boyacá", "Chivata"],
  ["Boyacá", "Chivor"],
  ["Boyacá", "Ciénega"],
  ["Boyacá", "Cómbita"],
  ["Boyacá", "Coper"],
  ["Boyacá", "Corrales"],
  ["Boyacá", "Covarachía"],
  ["Boyacá", "Cubará"],
  ["Boyacá", "Cucaita"],
  ["Boyacá", "Cuítiva"],
  ["Boyacá", "Duitama"],
  ["Boyacá", "El Cocuy"],
  ["Boyacá", "El Espino"],
  ["Boyacá", "Firavitoba"],
  ["Boyacá", "Floresta"],
  ["Boyacá", "Gachantivá"],
  ["Boyacá", "Gámeza"],
  ["Boyacá", "Garagoa"],
  ["Boyacá", "Guacamayas"],
  ["Boyacá", "Guateque"],
  ["Boyacá", "Guayatá"],
  ["Boyacá", "Güicán"],
  ["Boyacá", "Iza"],
  ["Boyacá", "Jenesano"],
  ["Boyacá", "Jericó"],
  ["Boyacá", "La Capilla"],
  ["Boyacá", "La Uvita"],
  ["Boyacá", "La Victoria"],
  ["Boyacá", "Labranzagrande"],
  ["Boyacá", "Macanal"],
  ["Boyacá", "Maripi"],
  ["Boyacá", "Miraflores"],
  ["Boyacá", "Mongua"],
  ["Boyacá", "Monguí"],
  ["Boyacá", "Moniquirá"],
  ["Boyacá", "Motavita"],
  ["Boyacá", "Muzo"],
  ["Boyacá", "Nobsa"],
  ["Boyacá", "Nuevo Colón"],
  ["Boyacá", "Oicatá"],
  ["Boyacá", "Otanche"],
  ["Boyacá", "Pachavita"],
  ["Boyacá", "Páez"],
  ["Boyacá", "Paipa"],
  ["Boyacá", "Pajarito"],
  ["Boyacá", "Panqueba"],
  ["Boyacá", "Pauna"],
  ["Boyacá", "Paya"],
  ["Boyacá", "Paz De Río"],
  ["Boyacá", "Pesca"],
  ["Boyacá", "Pisba"],
  ["Boyacá", "Puerto Boyacá"],
  ["Boyacá", "Quípama"],
  ["Boyacá", "Ramiriquí"],
  ["Boyacá", "Ráquira"],
  ["Boyacá", "Rondón"],
  ["Boyacá", "Saboya"],
  ["Boyacá", "Sáchica"],
  ["Boyacá", "Samacá"],
  ["Boyacá", "San Eduardo"],
  ["Boyacá", "San José De Pare"],
  ["Boyacá", "San Luis De Gaceno"],
  ["Boyacá", "San Mateo"],
  ["Boyacá", "San Miguel De Sema"],
  ["Boyacá", "San Pablo De Borbur"],
  ["Boyacá", "Santa María"],
  ["Boyacá", "Santa Rosa De Viterbo"],
  ["Boyacá", "Santa Sofía"],
  ["Boyacá", "Santana"],
  ["Boyacá", "Sativanorte"],
  ["Boyacá", "Sativasur"],
  ["Boyacá", "Siachoque"],
  ["Boyacá", "Soatá"],
  ["Boyacá", "Socha"],
  ["Boyacá", "Socotá"],
  ["Boyacá", "Sogamoso"],
  ["Boyacá", "Somondoco"],
  ["Boyacá", "Sora"],
  ["Boyacá", "Soracá"],
  ["Boyacá", "Sotaquirá"],
  ["Boyacá", "Susacón"],
  ["Boyacá", "Sutamarchan"],
  ["Boyacá", "Sutatenza"],
  ["Boyacá", "Tasco"],
  ["Boyacá", "Tenza"],
  ["Boyacá", "Tibaná"],
  ["Boyacá", "Tibasosa"],
  ["Boyacá", "Tinjacá"],
  ["Boyacá", "Tipacoque"],
  ["Boyacá", "Toca"],
  ["Boyacá", "Togüí"],
  ["Boyacá", "Tópaga"],
  ["Boyacá", "Tota"],
  ["Boyacá", "Tunja"],
  ["Boyacá", "Tunungua"],
  ["Boyacá", "Turmequé"],
  ["Boyacá", "Tuta"],
  ["Boyacá", "Tutazá"],
  ["Boyacá", "Úmbita"],
  ["Boyacá", "Ventaquemada"],
  ["Boyacá", "Villa De Leyva"],
  ["Boyacá", "Viracachá"],
  ["Boyacá", "Zetaquirá"],
  ["Caldas", "Aguadas"],
  ["Caldas", "Anserma"],
  ["Caldas", "Aranzazu"],
  ["Caldas", "Belalcazar"],
  ["Caldas", "Chinchiná"],
  ["Caldas", "Filadelfia"],
  ["Caldas", "La Dorada"],
  ["Caldas", "La Merced"],
  ["Caldas", "Manizales"],
  ["Caldas", "Manzanares"],
  ["Caldas", "Marmato"],
  ["Caldas", "Marquetalia"],
  ["Caldas", "Marulanda"],
  ["Caldas", "Neira"],
  ["Caldas", "Norcasia"],
  ["Caldas", "Pacora"],
  ["Caldas", "Palestina"],
  ["Caldas", "Pensilvania"],
  ["Caldas", "Riosucio"],
  ["Caldas", "Risaralda"],
  ["Caldas", "Salamina"],
  ["Caldas", "Samaná"],
  ["Caldas", "San José"],
  ["Caldas", "Supía"],
  ["Caldas", "Victoria"],
  ["Caldas", "Villamaría"],
  ["Caldas", "Viterbo"],
  ["Caquetá", "Albania"],
  ["Caquetá", "Belén De Los Andaquies"],
  ["Caquetá", "Cartagena Del Chairá"],
  ["Caquetá", "Curillo"],
  ["Caquetá", "El Doncello"],
  ["Caquetá", "El Paujil"],
  ["Caquetá", "Florencia"],
  ["Caquetá", "La Montañita"],
  ["Caquetá", "Milán"],
  ["Caquetá", "Morelia"],
  ["Caquetá", "Puerto Rico"],
  ["Caquetá", "San José Del Fragua"],
  ["Caquetá", "San Vicente Del Caguán"],
  ["Caquetá", "Solano"],
  ["Caquetá", "Solita"],
  ["Caquetá", "Valparaíso"],
  ["Casanare", "Aguazul"],
  ["Casanare", "Chameza"],
  ["Casanare", "Hato Corozal"],
  ["Casanare", "La Salina"],
  ["Casanare", "Maní"],
  ["Casanare", "Monterrey"],
  ["Casanare", "Nunchía"],
  ["Casanare", "Orocué"],
  ["Casanare", "Paz De Ariporo "],
  ["Casanare", "Pore"],
  ["Casanare", "Recetor"],
  ["Casanare", "Sabanalarga"],
  ["Casanare", "Sácama"],
  ["Casanare", "San Luis De Palenque"],
  ["Casanare", "Támara"],
  ["Casanare", "Tauramena"],
  ["Casanare", "Trinidad"],
  ["Casanare", "Villanueva"],
  ["Casanare", "Yopal"],
  ["Cauca", "Almaguer"],
  ["Cauca", "Argelia"],
  ["Cauca", "Balboa"],
  ["Cauca", "Bolívar"],
  ["Cauca", "Buenos Aires"],
  ["Cauca", "Cajibio"],
  ["Cauca", "Caldono"],
  ["Cauca", "Caloto"],
  ["Cauca", "Corinto"],
  ["Cauca", "El Tambo"],
  ["Cauca", "Florencia"],
  ["Cauca", "Guachené"],
  ["Cauca", "Guapi"],
  ["Cauca", "Inzá"],
  ["Cauca", "Jambaló"],
  ["Cauca", "La Sierra"],
  ["Cauca", "La Vega"],
  ["Cauca", "López De Micay"],
  ["Cauca", "Mercaderes"],
  ["Cauca", "Miranda"],
  ["Cauca", "Morales"],
  ["Cauca", "Padilla"],
  ["Cauca", "Páez"],
  ["Cauca", "Patía"],
  ["Cauca", "Piamonte"],
  ["Cauca", "Piendamó"],
  ["Cauca", "Popayán"],
  ["Cauca", "Puerto Tejada"],
  ["Cauca", "Puracé"],
  ["Cauca", "Rosas"],
  ["Cauca", "San Sebastián"],
  ["Cauca", "Santa Rosa"],
  ["Cauca", "Santander De Quilichao"],
  ["Cauca", "Silvia"],
  ["Cauca", "Sotará"],
  ["Cauca", "Suárez"],
  ["Cauca", "Sucre"],
  ["Cauca", "Timbío"],
  ["Cauca", "Timbiquí"],
  ["Cauca", "Toribio"],
  ["Cauca", "Totoró"],
  ["Cauca", "Villa Rica"],
  ["Cesar", "Aguachica"],
  ["Cesar", "Agustín Codazzi"],
  ["Cesar", "Astrea"],
  ["Cesar", "Becerril"],
  ["Cesar", "Bosconia"],
  ["Cesar", "Chimichagua"],
  ["Cesar", "Chiriguaná"],
  ["Cesar", "Curumaní"],
  ["Cesar", "El Copey"],
  ["Cesar", "El Paso"],
  ["Cesar", "Gamarra"],
  ["Cesar", "González"],
  ["Cesar", "La Gloria"],
  ["Cesar", "La Jagua De Ibirico"],
  ["Cesar", "La Paz"],
  ["Cesar", "Manaure Balcón Del César"],
  ["Cesar", "Pailitas"],
  ["Cesar", "Pelaya"],
  ["Cesar", "Pueblo Bello"],
  ["Cesar", "Rio De Oro"],
  ["Cesar", "San Alberto"],
  ["Cesar", "San Diego"],
  ["Cesar", "San Martín "],
  ["Cesar", "Tamalameque"],
  ["Cesar", "Valledupar"],
  ["Chocó", "Acandí"],
  ["Chocó", "Alto Baudó"],
  ["Chocó", "Atrato"],
  ["Chocó", "Bagadó"],
  ["Chocó", "Bahía Solano "],
  ["Chocó", "Bajo Baudó"],
  ["Chocó", "Bojayá"],
  ["Chocó", "Carmen Del Darién"],
  ["Chocó", "Cértegui"],
  ["Chocó", "Condoto"],
  ["Chocó", "El Cantón de San Pablo"],
  ["Chocó", "El Carmen De Atrato"],
  ["Chocó", "El Litoral De San Juan"],
  ["Chocó", "Istmina"],
  ["Chocó", "Juradó"],
  ["Chocó", "Lloró"],
  ["Chocó", "Medio Atrato"],
  ["Chocó", "Medio Baudó"],
  ["Chocó", "Medio San Juan"],
  ["Chocó", "Nóvita"],
  ["Chocó", "Nuquí"],
  ["Chocó", "Quibdó"],
  ["Chocó", "Río Iró"],
  ["Chocó", "Río Quito"],
  ["Chocó", "Riosucio"],
  ["Chocó", "San José de Tadó"],
  ["Chocó", "San José Del Palmar"],
  ["Chocó", "Sipí"],
  ["Chocó", "Ungüía"],
  ["Chocó", "Unión Panamericana"],
  ["Córdoba", "Ayapel"],
  ["Córdoba", "Buenavista"],
  ["Córdoba", "Canalete"],
  ["Córdoba", "Cereté"],
  ["Córdoba", "Chimá"],
  ["Córdoba", "Chinú"],
  ["Córdoba", "Ciénaga De Oro "],
  ["Córdoba", "Cotorra"],
  ["Córdoba", "La Apartada"],
  ["Córdoba", "Los Córdobas"],
  ["Córdoba", "Momil"],
  ["Córdoba", "Montelibano"],
  ["Córdoba", "Montería"],
  ["Córdoba", "Moñitos"],
  ["Córdoba", "Planeta Rica"],
  ["Córdoba", "Pueblo Nuevo"],
  ["Córdoba", "Puerto Escondido"],
  ["Córdoba", "Puerto Libertador"],
  ["Córdoba", "Purísima"],
  ["Córdoba", "Sahagún"],
  ["Córdoba", "San Andrés De Sotavento"],
  ["Córdoba", "San Antero"],
  ["Córdoba", "San Bernardo Del Viento"],
  ["Córdoba", "San Carlos"],
  ["Córdoba", "San José De Uré"],
  ["Córdoba", "San Pelayo"],
  ["Córdoba", "Santa Cruz De Lorica"],
  ["Córdoba", "Tierralta"],
  ["Córdoba", "Tuchín"],
  ["Córdoba", "Valencia"],
  ["Cundinamarca", "Agua De Dios "],
  ["Cundinamarca", "Albán"],
  ["Cundinamarca", "Anapoima"],
  ["Cundinamarca", "Anolaima"],
  ["Cundinamarca", "Apulo"],
  ["Cundinamarca", "Arbeláez"],
  ["Cundinamarca", "Beltrán"],
  ["Cundinamarca", "Bituima"],
  ["Bogotá D.C.", "Bogotá D.C."],
  ["Cundinamarca", "Bojacá"],
  ["Cundinamarca", "Cabrera"],
  ["Cundinamarca", "Cachipay"],
  ["Cundinamarca", "Cajicá"],
  ["Cundinamarca", "Caparrapí"],
  ["Cundinamarca", "Cáqueza"],
  ["Cundinamarca", "Carmen De Carupa"],
  ["Cundinamarca", "Chaguaní"],
  ["Cundinamarca", "Chía"],
  ["Cundinamarca", "Chipaque"],
  ["Cundinamarca", "Choachí"],
  ["Cundinamarca", "Chocontá"],
  ["Cundinamarca", "Cogua"],
  ["Cundinamarca", "Cota"],
  ["Cundinamarca", "Cucunubá"],
  ["Cundinamarca", "El Colegio"],
  ["Cundinamarca", "El Peñón"],
  ["Cundinamarca", "El Rosal"],
  ["Cundinamarca", "Facatativá"],
  ["Cundinamarca", "Fómeque"],
  ["Cundinamarca", "Fosca"],
  ["Cundinamarca", "Funza"],
  ["Cundinamarca", "Fúquene"],
  ["Cundinamarca", "Fusagasugá"],
  ["Cundinamarca", "Gachalá"],
  ["Cundinamarca", "Gachancipá"],
  ["Cundinamarca", "Gachetá"],
  ["Cundinamarca", "Gama"],
  ["Cundinamarca", "Girardot"],
  ["Cundinamarca", "Granada"],
  ["Cundinamarca", "Guachetá"],
  ["Cundinamarca", "Guaduas"],
  ["Cundinamarca", "Guasca"],
  ["Cundinamarca", "Guataquí"],
  ["Cundinamarca", "Guatavita"],
  ["Cundinamarca", "Guayabal De Siquima"],
  ["Cundinamarca", "Guayabetal"],
  ["Cundinamarca", "Gutierrez"],
  ["Cundinamarca", "Jerusalen"],
  ["Cundinamarca", "Junín"],
  ["Cundinamarca", "La Calera"],
  ["Cundinamarca", "La Mesa"],
  ["Cundinamarca", "La Palma"],
  ["Cundinamarca", "La Peña"],
  ["Cundinamarca", "La Vega"],
  ["Cundinamarca", "Lenguazaque"],
  ["Cundinamarca", "Machetá"],
  ["Cundinamarca", "Madrid"],
  ["Cundinamarca", "Manta"],
  ["Cundinamarca", "Medina"],
  ["Cundinamarca", "Mosquera"],
  ["Cundinamarca", "Nariño"],
  ["Cundinamarca", "Nemocón"],
  ["Cundinamarca", "Nilo"],
  ["Cundinamarca", "Nimaima"],
  ["Cundinamarca", "Nocaima"],
  ["Cundinamarca", "Pacho"],
  ["Cundinamarca", "Paime"],
  ["Cundinamarca", "Pandi"],
  ["Cundinamarca", "Paratebueno"],
  ["Cundinamarca", "Pasca"],
  ["Cundinamarca", "Puerto Salgar"],
  ["Cundinamarca", "Pulí"],
  ["Cundinamarca", "Quebradanegra"],
  ["Cundinamarca", "Quetame"],
  ["Cundinamarca", "Quipile"],
  ["Cundinamarca", "Ricaurte"],
  ["Cundinamarca", "San Antonio Del Tequendama"],
  ["Cundinamarca", "San Bernardo"],
  ["Cundinamarca", "San Cayetano"],
  ["Cundinamarca", "San Francisco"],
  ["Cundinamarca", "San Juan De Rioseco"],
  ["Cundinamarca", "Sasaima"],
  ["Cundinamarca", "Sesquilé"],
  ["Cundinamarca", "Sibaté"],
  ["Cundinamarca", "Silvania"],
  ["Cundinamarca", "Simijaca"],
  ["Cundinamarca", "Soacha"],
  ["Cundinamarca", "Sopó"],
  ["Cundinamarca", "Subachoque"],
  ["Cundinamarca", "Suesca"],
  ["Cundinamarca", "Supatá"],
  ["Cundinamarca", "Susa"],
  ["Cundinamarca", "Sutatausa"],
  ["Cundinamarca", "Tabio"],
  ["Cundinamarca", "Tausa"],
  ["Cundinamarca", "Tena"],
  ["Cundinamarca", "Tenjo"],
  ["Cundinamarca", "Tibacuy"],
  ["Cundinamarca", "Tibirita"],
  ["Cundinamarca", "Tocaima"],
  ["Cundinamarca", "Tocancipá"],
  ["Cundinamarca", "Topaipi"],
  ["Cundinamarca", "Ubalá"],
  ["Cundinamarca", "Ubaque"],
  ["Cundinamarca", "Ubate"],
  ["Cundinamarca", "Une"],
  ["Cundinamarca", "Útica"],
  ["Cundinamarca", "Venecia"],
  ["Cundinamarca", "Vergara"],
  ["Cundinamarca", "Vianí"],
  ["Cundinamarca", "Villagomez"],
  ["Cundinamarca", "Villapinzón"],
  ["Cundinamarca", "Villeta"],
  ["Cundinamarca", "Viotá"],
  ["Cundinamarca", "Yacopí"],
  ["Cundinamarca", "Zipacón"],
  ["Cundinamarca", "Zipaquirá"],
  ["Guainía", "Barrancominas"],
  ["Guainía", "Inirida"],
  ["Guaviare", "Calamar"],
  ["Guaviare", "El Retorno"],
  ["Guaviare", "Miraflores"],
  ["Guaviare", "San José Del Guaviare"],
  ["Huila", "Acevedo"],
  ["Huila", "Agrado"],
  ["Huila", "Aipe"],
  ["Huila", "Algeciras"],
  ["Huila", "Altamira"],
  ["Huila", "Baraya"],
  ["Huila", "Campoalegre"],
  ["Huila", "Colombia"],
  ["Huila", "Elías"],
  ["Huila", "Garzón"],
  ["Huila", "Gigante"],
  ["Huila", "Guadalupe"],
  ["Huila", "Hobo"],
  ["Huila", "Iquira"],
  ["Huila", "Isnos"],
  ["Huila", "La Argentina"],
  ["Huila", "La Plata "],
  ["Huila", "Nátaga"],
  ["Huila", "Neiva"],
  ["Huila", "Oporapa"],
  ["Huila", "Paicol"],
  ["Huila", "Palermo"],
  ["Huila", "Palestina"],
  ["Huila", "Pital"],
  ["Huila", "Pitalito"],
  ["Huila", "Rivera"],
  ["Huila", "Saladoblanco"],
  ["Huila", "San Agustín "],
  ["Huila", "Santa María "],
  ["Huila", "Suaza"],
  ["Huila", "Tarqui"],
  ["Huila", "Tello"],
  ["Huila", "Teruel"],
  ["Huila", "Tesalia"],
  ["Huila", "Timaná"],
  ["Huila", "Villavieja"],
  ["Huila", "Yaguará"],
  ["La Guajira", "Albania"],
  ["La Guajira", "Barrancas"],
  ["La Guajira", "Dibulla"],
  ["La Guajira", "Distracción"],
  ["La Guajira", "El Molino"],
  ["La Guajira", "Fonseca"],
  ["La Guajira", "Hatonuevo"],
  ["La Guajira", "La Jagua Del Pilar"],
  ["La Guajira", "Maicao"],
  ["La Guajira", "Manaure"],
  ["La Guajira", "Riohacha"],
  ["La Guajira", "San Juan Del Cesar"],
  ["La Guajira", "Uribia"],
  ["La Guajira", "Urumita"],
  ["La Guajira", "Villanueva"],
  ["Magdalena", "Algarrobo"],
  ["Magdalena", "Aracataca"],
  ["Magdalena", "Ariguaní"],
  ["Magdalena", "Cerro De San Antonio"],
  ["Magdalena", "Chivolo"],
  ["Magdalena", "Ciénaga"],
  ["Magdalena", "Concordia"],
  ["Magdalena", "El Banco"],
  ["Magdalena", "El Piñón"],
  ["Magdalena", "El Retén"],
  ["Magdalena", "Fundación"],
  ["Magdalena", "Guamal"],
  ["Magdalena", "Nueva Granada"],
  ["Magdalena", "Pedraza"],
  ["Magdalena", "Pijiño Del Carmen"],
  ["Magdalena", "Pivijay"],
  ["Magdalena", "Plato"],
  ["Magdalena", "Puebloviejo"],
  ["Magdalena", "Remolino"],
  ["Magdalena", "Sabanas De San Ángel"],
  ["Magdalena", "Salamina"],
  ["Magdalena", "San Sebastián De Buenavista"],
  ["Magdalena", "San Zenón"],
  ["Magdalena", "Santa Ana"],
  ["Magdalena", "Santa Bárbara De Pinto"],
  ["Magdalena", "Santa Marta"],
  ["Magdalena", "Sitionuevo"],
  ["Magdalena", "Tenerife"],
  ["Magdalena", "Zapayán"],
  ["Magdalena", "Zona Bananera"],
  ["Meta", "Acacías"],
  ["Meta", "Barranca De Upía"],
  ["Meta", "Cabuyaro"],
  ["Meta", "Castilla La Nueva"],
  ["Meta", "Cubarral"],
  ["Meta", "Cumaral"],
  ["Meta", "El Calvario"],
  ["Meta", "El Castillo"],
  ["Meta", "El Dorado"],
  ["Meta", "Fuente De Oro"],
  ["Meta", "Granada"],
  ["Meta", "Guamal"],
  ["Meta", "La Macarena"],
  ["Meta", "Lejanias"],
  ["Meta", "Mapiripán"],
  ["Meta", "Mesetas"],
  ["Meta", "Puerto Concordia"],
  ["Meta", "Puerto Gaitán "],
  ["Meta", "Puerto Lleras"],
  ["Meta", "Puerto López"],
  ["Meta", "Puerto Rico"],
  ["Meta", "Restrepo"],
  ["Meta", "San Carlos De Guaroa"],
  ["Meta", "San Juan De Arama"],
  ["Meta", "San Juanito "],
  ["Meta", "San Martín De Los Llanos"],
  ["Meta", "Uribe"],
  ["Meta", "Villavicencio"],
  ["Meta", "Vista Hermosa"],
  ["Nariño", "Alban"],
  ["Nariño", "Aldana"],
  ["Nariño", "Ancuyá"],
  ["Nariño", "Arboleda"],
  ["Nariño", "Barbacoas"],
  ["Nariño", "Belén"],
  ["Nariño", "Buesaco"],
  ["Nariño", "Chachagüí"],
  ["Nariño", "Colón"],
  ["Nariño", "Consacá"],
  ["Nariño", "Contadero"],
  ["Nariño", "Córdoba"],
  ["Nariño", "Cuaspud"],
  ["Nariño", "Cumbal"],
  ["Nariño", "Cumbitara"],
  ["Nariño", "El Charco"],
  ["Nariño", "El Peñol"],
  ["Nariño", "El Rosario"],
  ["Nariño", "El Tablón De Gómez"],
  ["Nariño", "El Tambo"],
  ["Nariño", "Francisco Pizarro"],
  ["Nariño", "Funes"],
  ["Nariño", "Guachucal"],
  ["Nariño", "Guaitarilla"],
  ["Nariño", "Gualmatán"],
  ["Nariño", "Iles"],
  ["Nariño", "Imués"],
  ["Nariño", "Ipiales"],
  ["Nariño", "La Cruz"],
  ["Nariño", "La Florida"],
  ["Nariño", "La Llanada"],
  ["Nariño", "La Tola"],
  ["Nariño", "La Unión"],
  ["Nariño", "Leiva"],
  ["Nariño", "Linares"],
  ["Nariño", "Los Andes"],
  ["Nariño", "Magüi Payán"],
  ["Nariño", "Mallama"],
  ["Nariño", "Mosquera"],
  ["Nariño", "Nariño"],
  ["Nariño", "Olaya Herrera "],
  ["Nariño", "Ospina"],
  ["Nariño", "Policarpa"],
  ["Nariño", "Potosí"],
  ["Nariño", "Providencia"],
  ["Nariño", "Puerres"],
  ["Nariño", "Pupiales"],
  ["Nariño", "Ricaurte"],
  ["Nariño", "Roberto Payán"],
  ["Nariño", "Samaniego"],
  ["Nariño", "San Bernardo"],
  ["Nariño", "San Juan De Pasto"],
  ["Nariño", "San Lorenzo"],
  ["Nariño", "San Pablo"],
  ["Nariño", "San Pedro De Cartago"],
  ["Nariño", "Sandoná"],
  ["Nariño", "Santa Bárbara"],
  ["Nariño", "Santacruz"],
  ["Nariño", "Sapuyes"],
  ["Nariño", "Taminango"],
  ["Nariño", "Tangua"],
  ["Nariño", "Tumaco"],
  ["Nariño", "Túquerres"],
  ["Nariño", "Yacuanquer"],
  ["Norte De Santander", "Abrego"],
  ["Norte De Santander", "Arboledas"],
  ["Norte De Santander", "Bochalema"],
  ["Norte De Santander", "Bucarasica"],
  ["Norte De Santander", "Cáchira"],
  ["Norte De Santander", "Cácota"],
  ["Norte De Santander", "Chinácota"],
  ["Norte De Santander", "Chitagá"],
  ["Norte De Santander", "Convención"],
  ["Norte De Santander", "Cucutilla"],
  ["Norte De Santander", "Durania"],
  ["Norte De Santander", "El Carmen"],
  ["Norte De Santander", "El Tarra"],
  ["Norte De Santander", "El Zulia"],
  ["Norte De Santander", "Gramalote"],
  ["Norte De Santander", "Hacarí"],
  ["Norte De Santander", "Herrán"],
  ["Norte De Santander", "La Esperanza"],
  ["Norte De Santander", "La Playa De Belén"],
  ["Norte De Santander", "Labateca"],
  ["Norte De Santander", "Los Patios"],
  ["Norte De Santander", "Lourdes"],
  ["Norte De Santander", "Mutiscua"],
  ["Norte De Santander", "Ocaña"],
  ["Norte De Santander", "Pamplona"],
  ["Norte De Santander", "Pamplonita"],
  ["Norte De Santander", "Puerto Santander"],
  ["Norte De Santander", "Ragonvalia"],
  ["Norte De Santander", "Salazar De Las Palmas"],
  ["Norte De Santander", "San Calixto"],
  ["Norte De Santander", "San Cayetano"],
  ["Norte De Santander", "San José De Cúcuta"],
  ["Norte De Santander", "Santiago"],
  ["Norte De Santander", "Sardinata"],
  ["Norte De Santander", "Silos"],
  ["Norte De Santander", "Teorama"],
  ["Norte De Santander", "Tibú"],
  ["Norte De Santander", "Toledo"],
  ["Norte De Santander", "Villa Caro"],
  ["Norte De Santander", "Villa Del Rosario"],
  ["Putumayo", "Colón"],
  ["Putumayo", "Mocoa"],
  ["Putumayo", "Orito"],
  ["Putumayo", "Puerto Asís"],
  ["Putumayo", "Puerto Caicedo"],
  ["Putumayo", "Puerto Guzmán"],
  ["Putumayo", "Puerto Leguizamo"],
  ["Putumayo", "San Francisco"],
  ["Putumayo", "San Miguel"],
  ["Putumayo", "Santiago"],
  ["Putumayo", "Sibundoy"],
  ["Putumayo", "Valle Del Guamuez"],
  ["Putumayo", "Villagarzón"],
  ["Quindío", "Armenia"],
  ["Quindío", "Buenavista"],
  ["Quindío", "Calarcá"],
  ["Quindío", "Circasia"],
  ["Quindío", "Córdoba"],
  ["Quindío", "Filandia"],
  ["Quindío", "Génova"],
  ["Quindío", "La Tebaida"],
  ["Quindío", "Montenegro"],
  ["Quindío", "Pijao"],
  ["Quindío", "Quimbaya"],
  ["Quindío", "Salento"],
  ["Risaralda", "Apía"],
  ["Risaralda", "Balboa"],
  ["Risaralda", "Belén De Umbría"],
  ["Risaralda", "Dosquebradas"],
  ["Risaralda", "Guática"],
  ["Risaralda", "La Celia"],
  ["Risaralda", "La Virginia"],
  ["Risaralda", "Marsella"],
  ["Risaralda", "Mistrato"],
  ["Risaralda", "Pereira"],
  ["Risaralda", "Pueblo Rico "],
  ["Risaralda", "Quinchía"],
  ["Risaralda", "Santa Rosa De Cabal"],
  ["Risaralda", "Santuario"],
  ["San Andrés", "Providencia"],
  ["Santander", "Aguada"],
  ["Santander", "Albania"],
  ["Santander", "Aratoca"],
  ["Santander", "Barbosa"],
  ["Santander", "Barichara"],
  ["Santander", "Barrancabermeja"],
  ["Santander", "Betulia"],
  ["Santander", "Bolívar"],
  ["Santander", "Bucaramanga"],
  ["Santander", "Cabrera"],
  ["Santander", "California"],
  ["Santander", "Capitanejo"],
  ["Santander", "Carcasí"],
  ["Santander", "Cepita"],
  ["Santander", "Cerrito"],
  ["Santander", "Charalá"],
  ["Santander", "Charta"],
  ["Santander", "Chimá"],
  ["Santander", "Chipatá"],
  ["Santander", "Cimitarra"],
  ["Santander", "Concepción"],
  ["Santander", "Confines"],
  ["Santander", "Contratación"],
  ["Santander", "Coromoro"],
  ["Santander", "Curití"],
  ["Santander", "El Carmen De Chucurí"],
  ["Santander", "El Guacamayo"],
  ["Santander", "El Peñón"],
  ["Santander", "El Playón"],
  ["Santander", "Encino"],
  ["Santander", "Enciso"],
  ["Santander", "Florián"],
  ["Santander", "Floridablanca"],
  ["Santander", "Galán"],
  ["Santander", "Gambita"],
  ["Santander", "Girón"],
  ["Santander", "Guaca"],
  ["Santander", "Guadalupe"],
  ["Santander", "Guapota"],
  ["Santander", "Guavatá"],
  ["Santander", "Güepsa"],
  ["Santander", "Hato"],
  ["Santander", "Jesús María"],
  ["Santander", "Jordán"],
  ["Santander", "La Belleza"],
  ["Santander", "La Paz"],
  ["Santander", "Landázuri"],
  ["Santander", "Lebrija"],
  ["Santander", "Los Santos "],
  ["Santander", "Macaravita"],
  ["Santander", "Málaga"],
  ["Santander", "Matanza"],
  ["Santander", "Mogotes"],
  ["Santander", "Molagavita"],
  ["Santander", "Ocamonte"],
  ["Santander", "Oiba"],
  ["Santander", "Onzaga"],
  ["Santander", "Palmar"],
  ["Santander", "Palmas Del Socorro"],
  ["Santander", "Paramo"],
  ["Santander", "Piedecuesta"],
  ["Santander", "Pinchote"],
  ["Santander", "Puente Nacional"],
  ["Santander", "Puerto Parra"],
  ["Santander", "Puerto Wilches"],
  ["Santander", "Rionegro"],
  ["Santander", "Sabana De Torres"],
  ["Santander", "San Andrés"],
  ["Santander", "San Benito"],
  ["Santander", "San Gil"],
  ["Santander", "San Joaquin"],
  ["Santander", "San José De Miranda"],
  ["Santander", "San Miguel"],
  ["Santander", "San Vicente Del Chucurí"],
  ["Santander", "Santa Bárbara"],
  ["Santander", "Santa Helena De Opon"],
  ["Santander", "Simacota"],
  ["Santander", "Socorro"],
  ["Santander", "Suaita"],
  ["Santander", "Sucre"],
  ["Santander", "Surata"],
  ["Santander", "Tona"],
  ["Santander", "Valle De San José"],
  ["Santander", "Vélez"],
  ["Santander", "Vetas"],
  ["Santander", "Villanueva"],
  ["Santander", "Zapatoca"],
  ["Sucre", "Buenavista"],
  ["Sucre", "Caimito"],
  ["Sucre", "Chalan"],
  ["Sucre", "Coloso"],
  ["Sucre", "Corozal"],
  ["Sucre", "Coveñas"],
  ["Sucre", "El Roble"],
  ["Sucre", "Galeras"],
  ["Sucre", "Guaranda"],
  ["Sucre", "La Unión"],
  ["Sucre", "Los Palmitos"],
  ["Sucre", "Majagual"],
  ["Sucre", "Morroa"],
  ["Sucre", "Ovejas"],
  ["Sucre", "San Antonio De Palmito"],
  ["Sucre", "Sampues"],
  ["Sucre", "San Benito Abad"],
  ["Sucre", "San Juan De Betulia"],
  ["Sucre", "San Marcos"],
  ["Sucre", "San Onofre"],
  ["Sucre", "San Pedro "],
  ["Sucre", "Sincé"],
  ["Sucre", "Sincelejo"],
  ["Sucre", "Sucre"],
  ["Sucre", "Santiago De Tolú"],
  ["Sucre", "Toluviejo"],
  ["Tolima", "Alpujarra"],
  ["Tolima", "Alvarado"],
  ["Tolima", "Ambalema"],
  ["Tolima", "Anzoátegui"],
  ["Tolima", "Armero"],
  ["Tolima", "Ataco"],
  ["Tolima", "Cajamarca"],
  ["Tolima", "Carmen De Apicalá"],
  ["Tolima", "Casabianca"],
  ["Tolima", "Chaparral"],
  ["Tolima", "Coello"],
  ["Tolima", "Coyaima"],
  ["Tolima", "Cunday"],
  ["Tolima", "Dolores"],
  ["Tolima", "El Espinal"],
  ["Tolima", "Falan"],
  ["Tolima", "Flandes"],
  ["Tolima", "Fresno"],
  ["Tolima", "El Guamo"],
  ["Tolima", "Herveo"],
  ["Tolima", "Honda"],
  ["Tolima", "Ibagué "],
  ["Tolima", "Icononzo"],
  ["Tolima", "Lérida"],
  ["Tolima", "Libano"],
  ["Tolima", "Mariquita"],
  ["Tolima", "Melgar"],
  ["Tolima", "Murillo"],
  ["Tolima", "Natagaima"],
  ["Tolima", "Ortega"],
  ["Tolima", "Palocabildo"],
  ["Tolima", "Piedras"],
  ["Tolima", "Planadas"],
  ["Tolima", "Prado"],
  ["Tolima", "Purificación"],
  ["Tolima", "Rioblanco"],
  ["Tolima", "Roncesvalles"],
  ["Tolima", "Rovira"],
  ["Tolima", "Saldaña"],
  ["Tolima", "San Antonio "],
  ["Tolima", "San Luis "],
  ["Tolima", "Santa Isabel"],
  ["Tolima", "Suarez"],
  ["Tolima", "Valle De San Juan"],
  ["Tolima", "Venadillo"],
  ["Tolima", "Villahermosa"],
  ["Tolima", "Villarrica"],
  ["Valle Del Cauca", "Alcalá"],
  ["Valle Del Cauca", "Andalucía"],
  ["Valle Del Cauca", "Ansermanuevo"],
  ["Valle Del Cauca", "Argelia"],
  ["Valle Del Cauca", "Bolívar"],
  ["Valle Del Cauca", "Buenaventura"],
  ["Valle Del Cauca", "Guadalajara De Buga"],
  ["Valle Del Cauca", "Bugalagrande"],
  ["Valle Del Cauca", "Caicedonia"],
  ["Valle Del Cauca", "Calima Del Darién"],
  ["Valle Del Cauca", "Candelaria"],
  ["Valle Del Cauca", "Cartago"],
  ["Valle Del Cauca", "Dagua"],
  ["Valle Del Cauca", "El Águila"],
  ["Valle Del Cauca", "El Cairo"],
  ["Valle Del Cauca", "El Cerrito"],
  ["Valle Del Cauca", "El Dovio"],
  ["Valle Del Cauca", "Florida"],
  ["Valle Del Cauca", "Ginebra"],
  ["Valle Del Cauca", "Guacarí"],
  ["Valle Del Cauca", "Jamundí"],
  ["Valle Del Cauca", "La Cumbre"],
  ["Valle Del Cauca", "La Unión"],
  ["Valle Del Cauca", "La Victoria"],
  ["Valle Del Cauca", "Obando"],
  ["Valle Del Cauca", "Palmira"],
  ["Valle Del Cauca", "Pradera"],
  ["Valle Del Cauca", "Restrepo"],
  ["Valle Del Cauca", "Riofrio"],
  ["Valle Del Cauca", "Roldanillo"],
  ["Valle Del Cauca", "San Pedro"],
  ["Valle Del Cauca", "Santiago De Cali"],
  ["Valle Del Cauca", "Sevilla"],
  ["Valle Del Cauca", "Toro"],
  ["Valle Del Cauca", "Trujillo"],
  ["Valle Del Cauca", "Tuluá"],
  ["Valle Del Cauca", "Ulloa"],
  ["Valle Del Cauca", "Versalles"],
  ["Valle Del Cauca", "Vijes"],
  ["Valle Del Cauca", "Yotoco"],
  ["Valle Del Cauca", "Yumbo"],
  ["Valle Del Cauca", "Zarzal"],
  ["Vaupés", "Caruru"],
  ["Vaupés", "Mitú"],
  ["Vaupés", "Taraira"],
  ["Vichada", "Cumaribo"],
  ["Vichada", "La Primavera"],
  ["Vichada", "Puerto Carreño"],
  ["Vichada", "Santa Rosalía"],
];
