export const namesFields = {
  id: "Id",
  operatorContract: "Contrato #",
  orderNumber: "Orden #",
  authorizationNumber: "Autorización #",
  client: "Cliente",
  patientName: "Paciente",
  idCard: "Cedula",
  userPhone: "Telefono",
  email: "Email",
  creationDate: "F. Tentativa",
  origin: "Origen",
  destination: "Destino",
  itinerary: "Itinerario",
  travelDate: "F.R. Viaje",
  quantity: "Cantidad",
  value: "Valor",
  netValue: "Valor Total",
  remarks: "Comentario",
  status: "Estado",
  approvalDate: "F. Cumplimiento",
  ticketNumber: "Ticket #",
  ticketImage: "Ticket Imagen",
  operator: "Operador",
  backticketHistory: "Back Ticket History",
};
